# Generated by Django 3.1.3 on 2020-11-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0002_auto_20201113_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountheads',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heads.accountheads'),
        ),
    ]
