# Generated by Django 3.1.3 on 2020-11-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0004_auto_20201113_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountheads',
            old_name='classification',
            new_name='category',
        ),
    ]
