# Generated by Django 3.1.3 on 2020-11-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0005_auto_20201113_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountheads',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heads.accountheads')),
            ],
        ),
    ]
