# Generated by Django 3.1.3 on 2020-11-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0007_auto_20201114_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('interest_debit_applicable', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('interest_credit_applicable', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('frequency', models.CharField(choices=[('M', 'Monthly'), ('H', 'Half Yearly'), ('Y', 'Yearly')], max_length=1)),
                ('credit_interest_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditint', to='heads.account')),
                ('debit_interest_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='heads.account')),
                ('interest_debit_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heads.interesttable')),
            ],
        ),
    ]
