# Generated by Django 3.1.3 on 2020-11-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0008_interesttable_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='credit_interest_account',
            field=models.CharField(choices=[('S', 'Same Account'), ('O', 'Other Account')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='debit_interest_account',
            field=models.CharField(choices=[('S', 'Same Account'), ('O', 'Other Account')], max_length=1),
        ),
    ]
