# Generated by Django 3.1.3 on 2020-11-14 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0009_auto_20201114_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='interest_debit_code',
            new_name='interest_debit_table',
        ),
        migrations.AddField(
            model_name='scheme',
            name='interest_credit_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creditinterst_table', to='heads.interesttable'),
            preserve_default=False,
        ),
    ]
