# Generated by Django 3.1.3 on 2020-11-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0013_auto_20201114_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='credit_interest_account',
            field=models.CharField(choices=[('S', 'Same Account'), ('O', 'Other Account')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='interest_credit_applicable',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='interest_credit_table',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditinterst_table', to='heads.interesttable'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='interest_debit_applicable',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1),
        ),
    ]
