# Generated by Django 3.1.3 on 2020-11-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0016_auto_20201114_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountheads',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heads.scheme'),
            preserve_default=False,
        ),
    ]
