# Generated by Django 3.1.3 on 2020-11-14 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0018_auto_20201114_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttable',
            name='interest_rate',
        ),
        migrations.CreateModel(
            name='InterestTableVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heads.interesttable')),
            ],
        ),
    ]
