# Generated by Django 3.1.3 on 2020-11-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0019_auto_20201114_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesttableversion',
            name='applicable_from',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
