# Generated by Django 3.1.3 on 2020-11-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0020_interesttableversion_applicable_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesttableversion',
            name='version',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
