# Generated by Django 3.1.3 on 2020-11-14 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0021_interesttableversion_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttableversion',
            name='version',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='debit_interest_account',
            field=models.CharField(blank=True, choices=[('S', 'Same Account'), ('O', 'Other Account')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='interest_debit_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heads.interesttable'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('value_date', models.DateField(default=datetime.date(2020, 11, 14))),
                ('debit_credit', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heads.account')),
            ],
        ),
    ]
