# Generated by Django 3.1.3 on 2020-11-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0022_auto_20201114_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='system_account',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
