# Generated by Django 3.1.3 on 2020-11-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0023_account_system_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heads.customerid'),
        ),
    ]
