# Generated by Django 2.2.7 on 2020-11-18 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0025_auto_20201114_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesttable',
            options={'permissions': [('can_create', 'Can Create'), ('can_verify', 'Can Verify')]},
        ),
        migrations.AlterField(
            model_name='customerid',
            name='name',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_date',
            field=models.DateField(default=datetime.date(2020, 11, 18)),
        ),
    ]
