# Generated by Django 3.1.3 on 2020-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heads', '0026_auto_20201118_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerid',
            name='father_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customerid',
            name='husband_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
